# Generated by Django 5.2.7 on 2026-03-09 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity')], max_length=255)),
                ('category', models.CharField(choices=[('cash', 'Cash'), ('investments', 'Investments'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('mortgage', 'Mortgage'), ('other', 'Other')], max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='accounts_type_64cd31_idx'), models.Index(fields=['is_active'], name='accounts_is_acti_5b02bd_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
