# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  prod.db.backup:
    desc: "Backup production database using greenmask"
    cmds:
      - docker compose -f compose.prod.yml run --rm greenmask dump --config /var/lib/workdir/config.yaml
  prod.db.backup.list:
    desc: "List production using greenmask"
    cmds:
      - docker compose -f compose.prod.yml run --rm greenmask list-dumps --config /var/lib/workdir/config.yaml
  prod.db.backup.clean:
    desc: "Clean up old backups using greenmask"
    cmds:
      - docker compose -f compose.prod.yml run --rm greenmask delete --retain-recent 7 --config /var/lib/workdir/config.yaml
  prod.db.restore.latest:
    desc: "Restore production database"
    cmds:
      - docker compose -f compose.prod.yml run --rm greenmask restore latest --config /var/lib/workdir/config.yaml
  dev.manage:
    desc: "Run Django management commands"
    dir: backend
    cmds:
      - poetry run python manage.py {{.CLI_ARGS}}
  dev.up:
    desc: "Start dev dependencies"
    cmds:
      - docker compose -f compose.dev.yml up postgres redis mailhog --wait
      - docker compose -f compose.dev.yml exec -it redis redis-cli FLUSHALL
  dev.down:
    desc: "Stop dev dependencies"
    cmds:
      - docker compose -f compose.dev.yml down --remove-orphans
  dev.api:
    desc: "Generate API specification"
    cmds:
      - task dev.api.be
      - task dev.api.fe
  dev.api.be:
    desc: "Generate API specification from BE"
    dir: backend
    cmds:
      - poetry run python manage.py spectacular --color --urlconf 'config.urls' --custom-settings core.api.api_settings --file ../docs/schema.yml --validate --fail-on-warn
      - poetry run python manage.py show_urls --format=pretty-json > ../docs/urls.json
  dev.api.fe:
    desc: "Generate API specification for FE"
    dir: frontend
    cmds:
      - yarn run api
  dev.coverage:
    env:
      DISABLE_EXTERNAL_API_CALLS: "1"
      DJANGO_SETTINGS_MODULE: "config.settings.test"
    dir: backend
    cmds:
      - poetry run coverage run manage.py test -b
      - poetry run coverage report -m
      - poetry run coverage xml
      - poetry run genbadge coverage -i coverage.xml -o ../docs/coverage.svg
  dev.lint:
    desc: "Format code"
    cmds:
      - task dev.lint.be
      - task dev.lint.fe
  dev.lint.be:
    desc: "Format code with ruff"
    dir: backend
    cmds:
      - poetry run ruff format
      - poetry run ruff check . --fix
      - poetry run ruff format
  dev.lint.fe:
    desc: "Format code with eslint and prettier"
    dir: frontend
    cmds:
      - yarn run format
      - yarn run build
  dev.generate_admin:
    desc: "Generate admin.py files for specific apps"
    dir: backend
    cmds:
      - poetry run python manage.py admin_generator {{.CLI_ARGS}} > {{.CLI_ARGS}}/admin.py
      - poetry run ruff check {{.CLI_ARGS}}/admin.py --fix --unsafe-fixes
  dev.install:
    desc: Install Frontend and Backend dependencies
    deps:
      - dev.install.be
      - dev.install.fe
    cmds:
      - prek install --overwrite
  dev.install.be:
    dir: backend
    cmds:
      - poetry install --all-groups
    silent: true
  dev.install.fe:
    dir: frontend
    cmds:
      - yarn install
    silent: true
