# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  dev.up:
    desc: "Start dev dependencies"
    cmds:
      - docker compose -f compose.dev.yml up -d postgres redis
      - docker compose -f compose.dev.yml exec -it redis redis-cli FLUSHALL
  dev.down:
    desc: "Stop dev dependencies"
    cmds:
      - docker compose -f compose.dev.yml down
