# Generated by Django 5.2.7 on 2026-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code_a', models.IntegerField()),
                ('currency_code_b', models.IntegerField()),
                ('monobank_date', models.IntegerField()),
                ('rate_buy', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('rate_sell', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('rate_cross', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('currency_code_a', 'currency_code_b')},
            },
        ),
    ]
