# Generated by Django 5.2.7 on 2026-03-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_records', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Balance Record',
                'verbose_name_plural': 'Balance Records',
                'db_table': 'balance_records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='balance_rec_date_48e073_idx'), models.Index(fields=['account'], name='balance_rec_account_968bd8_idx')],
            },
        ),
    ]
