# Generated by Django 5.2.7 on 2026-05-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_unique_together_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='TransactionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_imports', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Transaction Import',
                'verbose_name_plural': 'Transaction Imports',
                'db_table': 'transaction_imports',
                'unique_together': {('account', 'file_hash')},
            },
        ),
    ]
